import { supabase } from './supabase';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function saveReport(userId: string, data: any) {
    try {
        const { data: savedReport, error } = await supabase
            .from('reports')
            .insert([
                {
                    user_id: userId,
                    analysis_data: data,
                    // created_at is usually auto-generated by Supabase
                }
            ])
            .select()
            .single();

        if (error) {
            console.error('Error saving report:', error);
            throw error;
        }

        return savedReport;
    } catch (error) {
        console.error('Unexpected error saving report:', error);
        throw error;
    }
}
